#
# Manifest generated by puild.
# !! changes may be overwritten !!
#
# Generated by: David
#
# Generated on: 2025-02-04
#

@{

# ID used to uniquely identify this module
GUID = '445bea27-1714-4b71-98a6-5e4854ad712f'

# Version number of this module.
ModuleVersion = '0.2.4'

# Author of this module
Author = 'Purple Monkey'

# Company or vendor of this module
CompanyName = 'david@brettle.org.uk'

# Copyright statement for this module
Copyright = '(c) 2022 David. All rights reserved.'

# Copyright statement for this module
Description = 'Powershell tools for development of powershell modules.'

# Supported PSEditions
# CompatiblePSEditions = @()

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the PowerShell host required by this module
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    '.\Classes\XMLChildrenTransformer.ps1'
    '.\Private\Convert-AboutFileToMarkdown.ps1'
    '.\Private\Convert-HelpDescriptionToMarkdown.ps1'
    '.\Private\Convert-HelpExampleToMarkdown.ps1'
    '.\Private\Convert-HelpParameterToMarkdown.ps1'
    '.\Private\Convert-HelpSyntaxToMarkdown.ps1'
    '.\Private\ConvertTo-MarkdownTable.ps1'
    '.\Private\ConvertTo-NormalizedXMLItem.ps1'
    '.\Private\Get-ExpandedPath.ps1'
    '.\Private\New-MarkdownCodeBlock.ps1'
    '.\Private\New-MarkdownSection.ps1'
    '.\Private\New-XMLElement.ps1'
    '.\Public\Get-CommentBasedHelp.ps1'
    '.\Public\New-ConfigurationCommand.ps1'
    '.\Public\New-ObjectListCommand.ps1'
    '.\Public\New-ProxyCommand.ps1'
    '.\Public\New-TypeFormatData.ps1'
    '.\Public\Save-MarkdownHelp.ps1'
    '.\Public\Save-XMLHelp.ps1'
  )

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Get-CommentBasedHelp'
    'New-ConfigurationCommand'
    'New-ObjectListCommand'
    'New-ProxyCommand'
    'New-TypeFormatData'
    'Save-MarkdownHelp'
    'Save-XMLHelp'
  )

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    '.\puild.json'
    '.\PurpleDevTools.psd1'
    '.\Classes\XMLChildrenTransformer.ps1'
    '.\Private\Convert-AboutFileToMarkdown.ps1'
    '.\Private\Convert-HelpDescriptionToMarkdown.ps1'
    '.\Private\Convert-HelpExampleToMarkdown.ps1'
    '.\Private\Convert-HelpParameterToMarkdown.ps1'
    '.\Private\Convert-HelpSyntaxToMarkdown.ps1'
    '.\Private\ConvertTo-MarkdownTable.ps1'
    '.\Private\ConvertTo-NormalizedXMLItem.ps1'
    '.\Private\Get-ExpandedPath.ps1'
    '.\Private\New-MarkdownCodeBlock.ps1'
    '.\Private\New-MarkdownSection.ps1'
    '.\Private\New-XMLElement.ps1'
    '.\Public\Get-CommentBasedHelp.ps1'
    '.\Public\New-ConfigurationCommand.ps1'
    '.\Public\New-ObjectListCommand.ps1'
    '.\Public\New-ProxyCommand.ps1'
    '.\Public\New-TypeFormatData.ps1'
    '.\Public\Save-MarkdownHelp.ps1'
    '.\Public\Save-XMLHelp.ps1'
    '.\Templates\ConfigurationCommand\Get'
    '.\Templates\ConfigurationCommand\Set'
    '.\Templates\ObjectListCommand\Add'
    '.\Templates\ObjectListCommand\Get'
    '.\Templates\ObjectListCommand\New'
    '.\Templates\ObjectListCommand\Remove'
    '.\Templates\ObjectListCommand\Save'
    '.\Templates\ObjectListCommand\Set'
  )

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
  PSData = @{
    # External dependent modules of this module
    # ExternalModuleDependencies = @()
    
    # A URL to an icon representing this module.
    # IconUri = ''
    
    LicenseUri = 'https://github.com/purplemonkeymad/PurpleDevTools/blob/master/LICENSE'
    
    # Prerelease string of this module
    # Prerelease = ''
    
    ProjectUri = 'https://github.com/purplemonkeymad/PurpleDevTools'
    
    # ReleaseNotes of this module
    # ReleaseNotes = ''
    
    # Flag to indicate whether the module requires explicit user acceptance for install/update/save
    RequireLicenseAcceptance = $False
    
    Tags = @(
        'Development'
        'modules'
      )
    
    }
  
  }

}

